flex:
  version: 0.5.5
  workflows:
    build:
      command: ./mvnw spring-boot:build-image
    deploy:
      command: >
        docker run
        -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
        -e ENV=$ENV
        -v $PWD:/workdir
        jshimko/kube-tools-aws:3.7.0
        bash -c "cd /workdir && ./scripts/deploy.sh"
service:
  name: spring-boot-grpc-service
